# Site settings
title: "Typewriter"
description: "So I was feeling nostalgic."
baseurl: "/typewriter"
url: "http://kingsleep.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/alixedi
  - title: "git"
    url: http://github.com/alixedi
  - title: "rss"
    url: /feed.xml
